/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.vue;

import restaurant.Table;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author t.chaumette
 */
public class Caissier extends javax.swing.JFrame {
    private Modele modele;
    private float gainJournee = 0;

    /**
     * Creates new form Caissier
     */
    public Caissier() {
        modele = new Modele();
        initComponents();
        loadModele();
        updateComponents();
        gain.setText(Float.toString(gainJournee));
    }

    private void saveModele()    {
        try {
            RessouceManager.save(this.modele, "modele.save");
        } catch (Exception e) {
            System.out.println("Erreur lors de la sauvegarde du modele : " + e.getMessage());
        }
    }

    private void loadModele() {
        try {
            this.modele = (Modele) RessouceManager.load("modele.save");
            updateComponents();
        } catch (Exception e) {
            System.out.println("Erreur lors du chargement du modele : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableau = new javax.swing.JScrollPane();
        tableTableau = new javax.swing.JTable();
        tableOccupe = new javax.swing.JButton();
        tableLibre = new javax.swing.JButton();
        Text1 = new javax.swing.JLabel();
        prixCommande = new javax.swing.JTextField();
        encaisser = new javax.swing.JButton();
        Text2 = new javax.swing.JLabel();
        gain = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        tableau1 = new javax.swing.JScrollPane();
        tableTableau1 = new javax.swing.JTable();
        tableOccupe1 = new javax.swing.JButton();
        tableLibre1 = new javax.swing.JButton();

        tableTableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro table", "Occupé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableau.setViewportView(tableTableau);

        tableOccupe.setText("Occupé");

        tableLibre.setText("Libre");
        tableLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableLibreActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Text1.setText("Caissier");

        encaisser.setText("Payer");
        encaisser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encaisserActionPerformed(evt);
            }
        });

        Text2.setText("Gain de la journée :");

        gain.setText(" ");

        Text3.setText("Lister des tables");

        tableTableau1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro table", "Occupé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableau1.setViewportView(tableTableau1);

        tableOccupe1.setText("Occupé");
        tableOccupe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableOccupe1ActionPerformed(evt);
            }
        });

        tableLibre1.setText("Libre");
        tableLibre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableLibre1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prixCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(encaisser))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Text2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gain)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tableOccupe1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tableLibre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(tableau1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Text3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(Text1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prixCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encaisser))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text2)
                            .addComponent(gain)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableau1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableOccupe1)
                            .addComponent(tableLibre1)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateComponents() {
        updateTable();
    }

    private void updateTable() {
        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Numéro de la table");
        tableModel.addColumn("Est occupé");

        for (Table table : modele.getTables()) {
            tableModel.addRow(new Object[]{table.getStringNumero(), table.isOccupee()});
        }

        tableTableau1.setModel(tableModel);
    }

    private void tableLibre1ActionPerformed(java.awt.event.ActionEvent evt) {
        String numero = tableTableau1.getValueAt(tableTableau1.getSelectedRow(), 0).toString();

        Table table = modele.getTable(Integer.parseInt(numero));
        table.setOccupee(false);

        saveModele();
        updateTable();
    }

    private void tableOccupe1ActionPerformed(java.awt.event.ActionEvent evt) {
        String numero = tableTableau1.getValueAt(tableTableau1.getSelectedRow(), 0).toString();

        Table table = modele.getTable(Integer.parseInt(numero));
        table.setOccupee(true);

        saveModele();
        updateTable();
    }

    private void encaisserActionPerformed(java.awt.event.ActionEvent evt) {
        gainJournee += Float.parseFloat(prixCommande.getText());
        modele.addArgent(Float.parseFloat(prixCommande.getText()));

        gain.setText(Float.toString(gainJournee));
        saveModele();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caissier().setVisible(true);
            }
        });
    }

    private void tableLibreActionPerformed(java.awt.event.ActionEvent evt) {}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JButton encaisser;
    private javax.swing.JLabel gain;
    private javax.swing.JTextField prixCommande;
    private javax.swing.JButton tableLibre;
    private javax.swing.JButton tableLibre1;
    private javax.swing.JButton tableOccupe;
    private javax.swing.JButton tableOccupe1;
    private javax.swing.JTable tableTableau;
    private javax.swing.JTable tableTableau1;
    private javax.swing.JScrollPane tableau;
    private javax.swing.JScrollPane tableau1;
    // End of variables declaration//GEN-END:variables
}
