/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.vue;

import restaurant.Ingredient;
import restaurant.Plat;
import restaurant.Table;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author t.chaumette
 */
public class cuisiner extends javax.swing.JFrame {
    private Modele modele;
    /**
     * Creates new form cuisiner
     */
    public cuisiner() {
        modele = new Modele();
        initComponents();
        updateComponents();
        loadModele();

        // initialisation des composants
        commandeListe.setModel( new DefaultListModel());
        listeIngredient.setModel(new DefaultListModel());
    }


    private void saveModele()    {
        try {
            RessouceManager.save(this.modele, "modele.save");
        } catch (Exception e) {
            System.out.println("Erreur lors de la sauvegarde du modele : " + e.getMessage());
        }
    }

    private void loadModele() {
        try {
            this.modele = (Modele) RessouceManager.load("modele.save");
            updateComponents();
        } catch (Exception e) {
            System.out.println("Erreur lors du chargement du modele : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        tableListe = new javax.swing.JScrollPane();
        listeTable = new javax.swing.JList<>();
        afficherCommande = new javax.swing.JButton();
        CommandeListe = new javax.swing.JScrollPane();
        commandeListe = new javax.swing.JList<>();
        afficherIngredient = new javax.swing.JButton();
        finiCommande = new javax.swing.JButton();
        IngredientListe = new javax.swing.JScrollPane();
        listeIngredient = new javax.swing.JList<>();
        Text3 = new javax.swing.JLabel();
        ListeIngredients = new javax.swing.JScrollPane();
        listeIngredients = new javax.swing.JTable();
        Text4 = new javax.swing.JLabel();
        quantiteRem = new javax.swing.JTextField();
        ingreRem = new javax.swing.JButton();
        Text5 = new javax.swing.JLabel();
        PlatsList = new javax.swing.JScrollPane();
        platList = new javax.swing.JTable();
        actif = new javax.swing.JButton();
        inactif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Text1.setText("Cuisinier");

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Commandes");

        listeTable.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tableListe.setViewportView(listeTable);

        afficherCommande.setText("Afficher");
        afficherCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherCommandeActionPerformed(evt);
            }
        });

        commandeListe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        CommandeListe.setViewportView(commandeListe);

        afficherIngredient.setText("Afficher Ingredient");
        afficherIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherIngredientActionPerformed(evt);
            }
        });

        finiCommande.setText("Fini");
        finiCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finiCommandeActionPerformed(evt);
            }
        });

        listeIngredient.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        IngredientListe.setViewportView(listeIngredient);

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Liste des Ingredients");

        listeIngredients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Quantite"
            }
        ));
        ListeIngredients.setViewportView(listeIngredients);

        Text4.setText("Quantité :");

        ingreRem.setText("Retirer");
        ingreRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreRemActionPerformed(evt);
            }
        });

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Listes des plats");

        platList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Actif"
            }
        ));
        PlatsList.setViewportView(platList);

        actif.setText("Actif");
        actif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actifActionPerformed(evt);
            }
        });

        inactif.setText("Inactif");
        inactif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(Text1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tableListe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CommandeListe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IngredientListe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Text2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(afficherCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finiCommande)
                                    .addComponent(afficherIngredient))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Text4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(quantiteRem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ingreRem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(ListeIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlatsList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actif)
                            .addComponent(inactif))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IngredientListe)
                            .addComponent(tableListe)
                            .addComponent(CommandeListe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afficherCommande)
                            .addComponent(afficherIngredient)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListeIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finiCommande)
                    .addComponent(ingreRem)
                    .addComponent(quantiteRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text4))
                .addGap(65, 65, 65)
                .addComponent(Text5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlatsList, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inactif)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void updateComponents() {
        updateTableList();
        updateIngredientList();
        updatePlatList();
    }

    public void updateTableList() {
        DefaultListModel listModel = new DefaultListModel();

        for (Table table : modele.getTables()) {
            if (!table.getPlats().isEmpty()) {
                listModel.addElement(table.getStringNumero());
            }
        }

        listeTable.setModel(listModel);
    }

    public void updateCommandeList(Table table) {
        if (table == null) {
            return;
        }
        DefaultListModel listModel = new DefaultListModel();
        for (Plat plat : table.getPlats()) {
            listModel.addElement(plat.getNom());
        }
        commandeListe.setModel(listModel);
    }

    private void afficherCommandeActionPerformed(java.awt.event.ActionEvent evt) {
        String numero = listeTable.getSelectedValue();
        Table table = modele.getTable(Integer.parseInt(numero));

        updateCommandeList(table);
    }

    private void afficherIngredientActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = commandeListe.getSelectedValue();
        Plat plat = modele.getPlat(nom);

        DefaultListModel listModel = new DefaultListModel();
        for (Ingredient ingredient : plat.getIngredients()) {
            listModel.addElement(ingredient.getNom());
        }
        listeIngredient.setModel(listModel);
    }

    private void finiCommandeActionPerformed(java.awt.event.ActionEvent evt) {
        String numero = listeTable.getSelectedValue();
        Table table = modele.getTable(Integer.parseInt(numero));
        String nom = commandeListe.getSelectedValue();
        Plat plat = modele.getPlat(nom);

        for (Ingredient ingredient : plat.getIngredients()) {
            ingredient.setQuantite(ingredient.getQuantite() - 1);
        }

        haveEnoughIngredient(plat);

        table.removePlat(plat);

        updateComponents();
        updateCommandeList(table);
        saveModele();
    }



    public void updateIngredientList() {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Nom");
        tableModel.addColumn("Quantite");

        for (Ingredient ingredient : modele.getIngredients()) {
            tableModel.addRow(new Object[]{ingredient.getNom(), Integer.toString(ingredient.getQuantite())});
        }

        listeIngredients.setModel(tableModel);
    }

    private void ingreRemActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = listeIngredients.getValueAt(listeIngredients.getSelectedRow(), 0).toString();
        Ingredient ingredient = modele.getIngredient(nom);
        String strQuantite = quantiteRem.getText();
        int quantite = Integer.parseInt(strQuantite);

        ingredient.setQuantite(ingredient.getQuantite() - quantite);

        for (Plat plat : modele.getPlats()) {
            haveEnoughIngredient(plat);
        }

        updatePlatList();
        updateIngredientList();
        saveModele();
    }

    public void haveEnoughIngredient(Plat plat) {
        for (Ingredient ingredient : plat.getIngredients()) {
            if (ingredient.getQuantite() <= 0) {
                plat.setRealisable(false);
                return;
            }
        }
        plat.setRealisable(true);
    }


    private void updatePlatList() {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Nom");
        tableModel.addColumn("Actif");

        for (Plat plat : modele.getPlats()) {
            tableModel.addRow(new Object[]{plat.getNom(), plat.getRealisable()});
        }

        platList.setModel(tableModel);
    }



    private void actifActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = platList.getValueAt(platList.getSelectedRow(), 0).toString();
        Plat plat = modele.getPlat(nom);

        plat.setRealisable(true);

        updatePlatList();
        saveModele();
    }

    private void inactifActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = platList.getValueAt(platList.getSelectedRow(), 0).toString();
        Plat plat = modele.getPlat(nom);

        plat.setRealisable(false);

        updatePlatList();
        saveModele();
    }





    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuisiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuisiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuisiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuisiner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuisiner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CommandeListe;
    private javax.swing.JScrollPane IngredientListe;
    private javax.swing.JScrollPane ListeIngredients;
    private javax.swing.JScrollPane PlatsList;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JButton actif;
    private javax.swing.JButton afficherCommande;
    private javax.swing.JButton afficherIngredient;
    private javax.swing.JList<String> commandeListe;
    private javax.swing.JButton finiCommande;
    private javax.swing.JButton inactif;
    private javax.swing.JButton ingreRem;
    private javax.swing.JList<String> listeIngredient;
    private javax.swing.JTable listeIngredients;
    private javax.swing.JList<String> listeTable;
    private javax.swing.JTable platList;
    private javax.swing.JTextField quantiteRem;
    private javax.swing.JScrollPane tableListe;
    // End of variables declaration//GEN-END:variables
}
