/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.vue;

import restaurant.Ingredient;
import restaurant.Plat;
import restaurant.Table;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.lang.reflect.Array;
import java.util.ArrayList;

/**
 *
 * @author t.chaumette
 */
public class Manager extends javax.swing.JFrame {
    private Modele modele;


    /**
     * Creates new form Manager
     */
    public Manager() {
        modele = new Modele();
        initComponents();
        updateComponents();
        loadModele();
    }

    private void saveModele()    {
        try {
            RessouceManager.save(this.modele, "modele.save");
        } catch (Exception e) {
            System.out.println("Erreur lors de la sauvegarde du modele : " + e.getMessage());
        }
    }

    private void loadModele() {
        try {
            this.modele = (Modele) RessouceManager.load("modele.save");
            updateComponents();
        } catch (Exception e) {
            System.out.println("Erreur lors du chargement du modele : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texte1 = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        argents = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        listeDesPlats = new javax.swing.JScrollPane();
        listePlats = new javax.swing.JTable();
        editerPlat = new javax.swing.JButton();
        supprimerPlat = new javax.swing.JButton();
        Text2 = new javax.swing.JLabel();
        nomPlat = new javax.swing.JTextField();
        Text3 = new javax.swing.JLabel();
        prixPlat = new javax.swing.JTextField();
        Text4 = new javax.swing.JLabel();
        ingredientsDansPlat = new javax.swing.JScrollPane();
        ingredientsPlat = new javax.swing.JList<>();
        ajouterPlat = new javax.swing.JButton();
        modifierPlat = new javax.swing.JButton();
        Text5 = new javax.swing.JLabel();
        ListeTable = new javax.swing.JScrollPane();
        listeTable = new javax.swing.JList<>();
        ajouterTable = new javax.swing.JButton();
        ajouterTableField = new javax.swing.JTextField();
        supprimerTable = new javax.swing.JButton();
        Text6 = new javax.swing.JLabel();
        ListeIngredients = new javax.swing.JScrollPane();
        listeIngredients = new javax.swing.JTable();
        Text7 = new javax.swing.JLabel();
        nomIngredient = new javax.swing.JTextField();
        Text8 = new javax.swing.JLabel();
        quantiteIngredient = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        acheter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Texte1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Texte1.setText("Manager");

        text.setText("Argents : ");

        argents.setText(" ");

        Text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text.setText("Liste des plats ");

        listePlats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Prix", "Liste des ingredients"
            }
        ));
        listeDesPlats.setViewportView(listePlats);

        editerPlat.setText("editer");
        editerPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editerPlatActionPerformed(evt);
            }
        });

        supprimerPlat.setText("Supprimer");
        supprimerPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerPlatActionPerformed(evt);
            }
        });

        Text2.setText("Nom");

        nomPlat.setText("Nom");
        nomPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomPlatActionPerformed(evt);
            }
        });

        Text3.setText("Prix");

        prixPlat.setText("Prix");
        prixPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixPlatActionPerformed(evt);
            }
        });

        Text4.setText("Ingredients");

        ingredientsPlat.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ingredientsDansPlat.setViewportView(ingredientsPlat);

        ajouterPlat.setText("Ajouter");
        ajouterPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterPlatActionPerformed(evt);
            }
        });

        modifierPlat.setText("Modifier");
        modifierPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierPlatActionPerformed(evt);
            }
        });

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Listes des tables");

        listeTable.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListeTable.setViewportView(listeTable);

        ajouterTable.setText("Ajouter");
        ajouterTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterTableActionPerformed(evt);
            }
        });

        ajouterTableField.setText("numero");
        ajouterTableField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterTableFieldActionPerformed(evt);
            }
        });

        supprimerTable.setText("Supprimer");
        supprimerTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerTableActionPerformed(evt);
            }
        });

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Ingredients");

        listeIngredients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Quantité"
            }
        ));
        ListeIngredients.setViewportView(listeIngredients);

        Text7.setText("Nom");

        nomIngredient.setText("Nom");
        nomIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomIngredientActionPerformed(evt);
            }
        });

        Text8.setText("Quantité");

        quantiteIngredient.setText("1");

        Text9.setText("Total");

        total.setText(" ");

        acheter.setText("Acheter");
        acheter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acheterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listeDesPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Text2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(prixPlat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Text3)
                                                .addGap(97, 97, 97)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Text4)
                                            .addComponent(ingredientsDansPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ajouterPlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editerPlat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supprimerPlat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(modifierPlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ListeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(supprimerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ajouterTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ajouterTableField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(text)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(argents)
                                        .addGap(314, 314, 314)
                                        .addComponent(Texte1))
                                    .addComponent(Text)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ListeIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Text7)
                                                    .addComponent(nomIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Text9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Text8)
                                                    .addComponent(quantiteIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(acheter, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texte1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text)
                        .addComponent(argents)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text)
                    .addComponent(Text5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajouterTableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajouterTable)
                        .addGap(18, 18, 18)
                        .addComponent(supprimerTable))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ListeTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(listeDesPlats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(editerPlat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supprimerPlat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text2)
                            .addComponent(Text3)
                            .addComponent(Text4))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prixPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ingredientsDansPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajouterPlat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifierPlat)))
                .addGap(45, 45, 45)
                .addComponent(Text6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Text7)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Text8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantiteIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text9)
                            .addComponent(total))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acheter))
                    .addComponent(ListeIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomIngredientActionPerformed(ActionEvent evt) {}
    private void ajouterTableFieldActionPerformed(ActionEvent evt) {}
    private void prixPlatActionPerformed(ActionEvent evt) {}
    private void nomPlatActionPerformed(ActionEvent evt) {}


    private void updateComponents() {
        updateComponentIngre();
        updateComponentTable();
        updateComponentPlat();
    }


    private void updateComponentPlat() {
        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Nom");
        tableModel.addColumn("Prix");
        tableModel.addColumn("Ingredients");

        for (Plat plat : modele.getPlats()) {
            tableModel.addRow(new Object[]{plat.getNom(), plat.getPrix(), plat.getIngredients()});
        }

        listePlats.setModel(tableModel);

        DefaultListModel listModel = new DefaultListModel();
        ingredientsPlat.setModel(listModel);

        for (Ingredient ingredient : modele.getIngredients()) {
            listModel.addElement(ingredient.getNom());
        }

    }

    private void ajouterPlatActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = nomPlat.getText();
        float prix = Float.parseFloat(prixPlat.getText());
        ArrayList<String> ingredients = new ArrayList<String>(ingredientsPlat.getSelectedValuesList());
        ArrayList<Ingredient> ingres = new ArrayList<Ingredient>();
        for (String ingre : ingredients) {
            ingres.add(modele.getIngredient(ingre));
        }


        Plat plat = new Plat(nom, prix, ingres,true);
        modele.addPlat(plat);

        saveModele();
        updateComponentPlat();
    }

    private void supprimerPlatActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = listePlats.getValueAt(listePlats.getSelectedRow(), 0).toString();

        Plat plat = modele.getPlat(nom);
        modele.removePlat(plat);

        saveModele();
        updateComponentPlat();
    }

    private void editerPlatActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = listePlats.getValueAt(listePlats.getSelectedRow(), 0).toString();
        Plat plat = modele.getPlat(nom);

        nomPlat.setText(plat.getNom());
        prixPlat.setText(String.valueOf(plat.getPrix()));

    }

    private void modifierPlatActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = listePlats.getValueAt(listePlats.getSelectedRow(), 0).toString();
        Plat plat = modele.getPlat(nom);

        plat.setNom(nomPlat.getText());
        plat.setPrix(Float.parseFloat(prixPlat.getText()));
        ArrayList<String> ingredients = new ArrayList<String>(ingredientsPlat.getSelectedValuesList());
        ArrayList<Ingredient> ingres = new ArrayList<Ingredient>();
        for (String ingre : ingredients) {
            ingres.add(modele.getIngredient(ingre));
        }
        plat.setIngredients(ingres);

        saveModele();
        updateComponentPlat();
    }




    private void updateComponentTable() {
        DefaultListModel listModel = new DefaultListModel();

        for (Table table : modele.getTables()) {
            listModel.addElement(table.getNumero());
        }

        listeTable.setModel(listModel);
    }

    private void ajouterTableActionPerformed(java.awt.event.ActionEvent evt) {
        String numero = ajouterTableField.getText();

        Table table = new Table(Integer.parseInt(numero));
        modele.addTable(table);

        saveModele();
        updateComponentTable();
    }

    private void supprimerTableActionPerformed(java.awt.event.ActionEvent evt) {
        int numero = listeTable.getSelectedIndex();

        Table table = modele.getTable(numero);
        modele.removeTable(table);

        saveModele();
        updateComponentTable();
    }



    private void updateComponentIngre() {
        DefaultTableModel tableModel = new DefaultTableModel();

        tableModel.addColumn("Nom");
        tableModel.addColumn("Quantité");

        for (Ingredient ingredient : modele.getIngredients()) {
            tableModel.addRow(new Object[]{ingredient.getNom(), ingredient.getQuantite()});
        }

        listeIngredients.setModel(tableModel);

        DefaultListModel listModel = new DefaultListModel();
        ingredientsPlat.setModel(listModel);

        for (Ingredient ingredient : modele.getIngredients()) {
            listModel.addElement(ingredient.getNom());
        }

    }

    private void acheterActionPerformed(java.awt.event.ActionEvent evt) {
        String nom = nomIngredient.getText();
        int quantite = Integer.parseInt(quantiteIngredient.getText());

        if (modele.getIngredient(nom) == null) {
            Ingredient ingredient = new Ingredient(nom, quantite);
            modele.addIngredient(ingredient);
        } else {
            Ingredient ingredient = modele.getIngredient(nom);
            ingredient.setQuantite(ingredient.getQuantite() + quantite);
        }

        saveModele();
        updateComponentIngre();
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ListeIngredients;
    private javax.swing.JScrollPane ListeTable;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Texte1;
    private javax.swing.JButton acheter;
    private javax.swing.JButton ajouterPlat;
    private javax.swing.JButton ajouterTable;
    private javax.swing.JTextField ajouterTableField;
    private javax.swing.JLabel argents;
    private javax.swing.JButton editerPlat;
    private javax.swing.JScrollPane ingredientsDansPlat;
    private javax.swing.JList<String> ingredientsPlat;
    private javax.swing.JScrollPane listeDesPlats;
    private javax.swing.JTable listeIngredients;
    private javax.swing.JTable listePlats;
    private javax.swing.JList<String> listeTable;
    private javax.swing.JButton modifierPlat;
    private javax.swing.JTextField nomIngredient;
    private javax.swing.JTextField nomPlat;
    private javax.swing.JTextField prixPlat;
    private javax.swing.JTextField quantiteIngredient;
    private javax.swing.JButton supprimerPlat;
    private javax.swing.JButton supprimerTable;
    private javax.swing.JLabel text;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
